### ISSUE TITLE
--no-select causes 100% CPU usage and freeze

### ISSUE THREAD

**Issue by xircon** [bharadwaj-raju/TextSuggest#28] opened 2016-07-27 11:14 UTC
Have been on nights, so not opened my computer for a week.

Is it now --noselect?

You need to alter the github page.....

Steve

**Comment by bharadwaj-raju** [comment] 2016-07-27 11:28
`--noselect` has been changed to ~~`--no-select`~~ `--no-selection` for consistency with other software and clarity.

Other options, too, have been altered, and the README updated.

**Comment by xircon** [comment] 2016-07-27 11:33
Then you need to change the post-install section on the front page:

Post-install

Assign keyboard shortcuts to

```
textsuggest
textsuggest --no-selection
```

**Comment by bharadwaj-raju** [comment] 2016-07-27 11:35
Perhaps you're looking at an old/cached version?

[![Screenshot of README](http://i.imgur.com/WfGMHih.png)](http://i.imgur.com/WfGMHih.png)

**Comment by bharadwaj-raju** [comment] 2016-07-27 11:37
I'm sorry, got confused. It _is_ `--no-selection`, but Python 3 argparse allows option abbreviation like using `--no-se` instead of `--no-selection`: basically make it a substring.

**Comment by xircon** [comment] 2016-07-27 11:44
Hmmm as I said, not opened computer for a week.  Tried to update the aur package and it fails, will report to maintainer.

On r48.24e215a-1 --no-selection does not work, but --noselect does

See screenshot - I am playing with xfce, so it is the keyboard short cut manager

![xfce4-textsuggest](https://cloud.githubusercontent.com/assets/1316691/17174205/ade65e16-53f7-11e6-91e8-d8eb899382f8.png)

**Comment by xircon** [comment] 2016-07-27 11:45
sorry :)
![xfce4-textsuggest-1](https://cloud.githubusercontent.com/assets/1316691/17174250/0133655a-53f8-11e6-92f3-ac3cac683a94.png)
Scrolled it in error

**Comment by bharadwaj-raju** [comment] 2016-07-27 11:46
Dash between `no` and `select`, making `--no-select`.

Although AUR package is probably broken. Use `install.sh` for now.

**Comment by xircon** [comment] 2016-07-27 11:48
Have reported...
https://aur.archlinux.org/packages/textsuggest-git/#news

**Comment by bharadwaj-raju** [comment] 2016-07-27 11:48
The `--noselect` to `--no-select` happened with some major changes, breaking AUR package.

**Comment by bharadwaj-raju** [comment] 2016-07-27 11:52
Apparently AUR requires some extras, so shellkr can't just use `install.sh`

**Comment by xircon** [comment] 2016-07-27 11:54
Will do.

Have run install.sh, now get:
`
textsuggest --no-selection                          
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 374, in <module>
    main()
  File "/usr/bin/textsuggest", line 351, in main
    words_list = get_suggestions(current_word, dict_files=get_dictionaries())
  File "/usr/lib/python3.5/suggestions.py", line 26, in get_suggestions
    with open(dictionary) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/steve/.config/textsuggest/Extra_Words.txt'
`

**Comment by bharadwaj-raju** [comment] 2016-07-27 11:56
Oh no. Fixing...

**Comment by xircon** [comment] 2016-07-27 11:57
Sorry for all the hassle :)
Tried:
cp /home/steve/TextSuggest/textsuggest/Extra_Words.txt /home/steve/.config/textsuggest/Extra_Words.txt 

But now it just hangs - no window appears.

**Comment by xircon** [comment] 2016-07-27 11:58
And sends my fan into over drive, 3 python3 processes running at 100% - have killed in htop

**Comment by bharadwaj-raju** [comment] 2016-07-27 12:02
Try latest again (just committed)

**Comment by xircon** [comment] 2016-07-27 12:09
Not working - no rofi window appears, processor and fan running like crazy:
![xfce4-textsuggest-2](https://cloud.githubusercontent.com/assets/1316691/17174722/61db4794-53fb-11e6-878b-5a041754e3ca.png)

**Comment by bharadwaj-raju** [comment] 2016-07-27 12:13
... Now?

**Comment by xircon** [comment] 2016-07-27 12:14
Hang on....

**Comment by xircon** [comment] 2016-07-27 12:16
No - still no rofi window, no errors and processor racing at 100%

**Comment by bharadwaj-raju** [comment] 2016-07-27 12:31
Now?

**Comment by bharadwaj-raju** [comment] 2016-07-27 12:32
Try getting the source tree and running `python3 TextSuggest.py` from there.

**Comment by xircon** [comment] 2016-07-27 13:14
python3 TextSuggest.py
Traceback (most recent call last):
  File "TextSuggest.py", line 196, in <module>
    current_word = sp.check_output(['xsel'])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    *_kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(_popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'xsel'

So installed xsel.....

python3 TextSuggest.py working as expected

python3 TextSuggest.py --no-selection does not bring up a rofi window.  Press  ctrl+c:

python3 TextSuggest.py --no-selection
^CTraceback (most recent call last):
  File "TextSuggest.py", line 376, in <module>
    main()
  File "TextSuggest.py", line 366, in main
    if hist_word.rstrip('\r\n') in words_list:
KeyboardInterrupt

**Comment by xircon** [comment] 2016-07-27 13:16
In install.sh this line is wrong......

if hash **xclip** 2>/dev/null; then
    echo "xsel\tOK..."

:edit:
also the echo lines should look like:
echo -e "Rofi \t OK..."

**Comment by bharadwaj-raju** [comment] 2016-07-27 19:27
The `install.sh` is wrong, and I _think_ I can solve the `--no-selection` problem easily.

But right now, I have to go. Will fix tomorrow.

**Comment by bharadwaj-raju** [comment] 2016-07-30 05:21
Now?

**Comment by bharadwaj-raju** [comment] 2016-07-30 05:22
Also try running `--no-selection` with `--no-history`.

**Comment by bharadwaj-raju** [comment] 2016-07-30 05:36
Now it should be fixed. The cause was a very stupid infinite-loop by me, now fixed.

**Comment by xircon** [comment] 2016-08-01 20:00
Apologies, work for the health service in UK, work shifts, worked all weekend.

Still no window on --no-selection

**Comment by bharadwaj-raju** [comment] 2016-08-02 11:33
@xircon On latest?

Any errors? Especially on `python3 TextSuggest.py --no-selection`.

**Comment by xircon** [comment] 2016-08-02 11:44
Yes, cloned and ran install.sh

No errors - processor races away. Ran from the clone I made yesterday.

**Comment by bharadwaj-raju** [comment] 2016-08-02 11:46
`--no-history`?

**Comment by xircon** [comment] 2016-08-02 11:49
rofi window appears on 

python3 TextSuggest.py --no-selection --no-history

**Comment by bharadwaj-raju** [comment] 2016-08-02 11:57
So that's a problem with the history implementation. Will fix.

**Comment by xircon** [comment] 2016-08-02 11:58
Cheers :)

**Comment by bharadwaj-raju** [comment] 2016-08-06 13:26
Now? (Remember to: download [latest](https://github.com/bharadwaj-raju/TextSuggest/archive/master.zip), and run with `python3 TextSuggest.py --no-selection` so we can see errors.)

I am baffled by this: I don't face this issue, even though we're on almost-same platforms (Arch Linux + Xfce).

**Comment by bharadwaj-raju** [comment] 2016-08-06 13:30
I'm thinking of just removing the history part, using _Rofi's_ history implementation: `rofi -no-disable-history`.

**Comment by xircon** [comment] 2016-08-06 17:22
Have completely removed manually, when I reinstall and run

```
python3 TextSuggest.py --no-selection
```

I get

```
Traceback (most recent call last):
  File "TextSuggest.py", line 390, in <module>
    main()
  File "TextSuggest.py", line 352, in main
    words_list = get_suggestions(current_word, dict_files=get_dictionaries())
  File "TextSuggest.py", line 213, in get_dictionaries
    for file in os.listdir(os.path.join(base_dict_dir, lang)):
PermissionError: [Errno 13] Permission denied: '/usr/share/textsuggest/dictionaries/English'
```

Looks like the dictionaries do not get installed:

```
sudo updatedb                        
 ✝  ~/Downloads/TextSuggest-master  locate -i textsuggest                
/home/steve/.config/textsuggest
/home/steve/.local/share/RecentDocuments/TextSuggest-master(1).zip.desktop
/home/steve/Downloads/TextSuggest-master
/home/steve/Downloads/TextSuggest-master.zip
/home/steve/Downloads/TextSuggest-master/.gitignore
/home/steve/Downloads/TextSuggest-master/LICENSE
/home/steve/Downloads/TextSuggest-master/README.md
/home/steve/Downloads/TextSuggest-master/TextSuggest.py
/home/steve/Downloads/TextSuggest-master/__pycache__
/home/steve/Downloads/TextSuggest-master/docs
/home/steve/Downloads/TextSuggest-master/fonts.py
/home/steve/Downloads/TextSuggest-master/install.sh
/home/steve/Downloads/TextSuggest-master/languages.py
/home/steve/Downloads/TextSuggest-master/libscreenkey
/home/steve/Downloads/TextSuggest-master/suggestions.py
/home/steve/Downloads/TextSuggest-master/textsuggest
/home/steve/Downloads/TextSuggest-master/textsuggestd
/home/steve/Downloads/TextSuggest-master/__pycache__/fonts.cpython-35.pyc
/home/steve/Downloads/TextSuggest-master/__pycache__/languages.cpython-35.pyc
/home/steve/Downloads/TextSuggest-master/__pycache__/suggestions.cpython-35.pyc
/home/steve/Downloads/TextSuggest-master/docs/textsuggest.1
/home/steve/Downloads/TextSuggest-master/docs/textsuggest.1.md
/home/steve/Downloads/TextSuggest-master/libscreenkey/inputlistener.py
/home/steve/Downloads/TextSuggest-master/libscreenkey/keysyms.py
/home/steve/Downloads/TextSuggest-master/libscreenkey/labelmanager.py
/home/steve/Downloads/TextSuggest-master/libscreenkey/xlib.py
/home/steve/Downloads/TextSuggest-master/textsuggest/Custom_Words.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/Extra_Words.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries
/home/steve/Downloads/TextSuggest-master/textsuggest/history.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/Bangla
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/Bangla/dict.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/A.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/B.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/C.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/D.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/E.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/F.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/G.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/H.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/I.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/J.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/K.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/L.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/M.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/N.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/O.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/P.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/Q.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/R.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/S.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/T.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/U.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/V.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/W.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/X.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/Y.txt
/home/steve/Downloads/TextSuggest-master/textsuggest/dictionaries/English/Z.txt
/home/steve/Pictures/xfce4-textsuggest-1.png
/home/steve/Pictures/xfce4-textsuggest-2.png
/home/steve/Pictures/xfce4-textsuggest.png
/usr/bin/textsuggest
/usr/share/textsuggest
/usr/share/doc/textsuggest
/usr/share/doc/textsuggest/README
/usr/share/licenses/textsuggest
/usr/share/licenses/textsuggest/COPYING
/usr/share/man/man1/textsuggest.1
/usr/share/man/man1/textsuggest.1.gz
```

**Comment by bharadwaj-raju** [comment] 2016-08-06 17:26
Looks like `install.sh` is a bit broken. Will fix just now...

Also, what happens on `ls /usr/share/textsuggest/dictionaries/`?

**Comment by bharadwaj-raju** [comment] 2016-08-06 17:29
Now?

**Comment by xircon** [comment] 2016-08-06 17:31
nope they are there, updatedb must not index /usr/share - so it is a permissions problem.

I had to su to do this.

```
 cd /usr/share/textsuggest/dictionaries
[root@steve-pc dictionaries]# ls
Bangla/  English/
[root@steve-pc dictionaries]# cd English/
[root@steve-pc English]# ls
A.txt  C.txt  E.txt  G.txt  I.txt  K.txt  M.txt  O.txt  Q.txt  S.txt  U.txt  W.txt  Y.txt
B.txt  D.txt  F.txt  H.txt  J.txt  L.txt  N.txt  P.txt  R.txt  T.txt  V.txt  X.txt  Z.txt
[root@steve-pc English]# 
```

**Comment by bharadwaj-raju** [comment] 2016-08-06 17:32
While permissions are now fixed in `install.sh`, this is the fix:

``` bash
$ sudo chmod -R a+r /usr/share/textsuggest
```

**Comment by xircon** [comment] 2016-08-06 17:35
OK re-downloaded, installed, fixed permissions - new error:

```
sudo chmod -R a+r /usr/share/textsuggest
 ✝  ~/Downloads/TextSuggest-master  python3 TextSuggest.py --no-selection   
Traceback (most recent call last):
  File "TextSuggest.py", line 134, in <module>
    language = [get_language_name(), 'English']
  File "/home/steve/Downloads/TextSuggest-master/languages.py", line 44, in get_language_name
    keyboard_layout = sp.check_output(keyboard_layout_cmd_str).decode('utf-8').rstrip()
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: "setxkbmap -print | awk -F '(+|\\()' '/xkb_symbols/ {print $2}'"
```

**Comment by bharadwaj-raju** [comment] 2016-08-06 17:37
Now? (Missed a `shell=True` on `subprocess.check_output()`)

**Comment by xircon** [comment] 2016-08-06 17:38
```
 python3 TextSuggest.py --no-selection
awk: warning: escape sequence `\(' treated as plain `('
awk: fatal: :, [., or [=: /(+|()/
Traceback (most recent call last):
  File "TextSuggest.py", line 134, in <module>
    language = [get_language_name(), 'English']
  File "/home/steve/Downloads/TextSuggest-master/languages.py", line 44, in get_language_name
    keyboard_layout = sp.check_output(keyboard_layout_cmd_str, shell=True).decode('utf-8').rstrip()
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'setxkbmap -print | awk -F '(+|\()' '/xkb_symbols/ {print $2}'' returned non-zero exit status 2
```

**Comment by xircon** [comment] 2016-08-06 17:40
Back in an hour or so, got to nip out.

**Comment by bharadwaj-raju** [comment] 2016-08-06 17:58
Meanwhile, fixed.

**Comment by shellkr** [comment] 2016-08-07 11:22
You shouldn't need to chmod in the install.sh. The 'cp -rf' command will do that already.

**Comment by bharadwaj-raju** [comment] 2016-08-07 12:18
@shellkr Yes, permissions are alright on my machine (fresh install from `install.sh`) but are root-owned on some.

**Comment by xircon** [comment] 2016-08-12 23:55
Working now, did a clean install.

The install.sh does not create the history or custom words files so it crashes, create these and it runs.

Apologies for the delay in replying, but I have been on night shifts all week :)

**Comment by bharadwaj-raju** [comment] 2016-08-13 07:41
Great! Will fix the `install.sh`...

**Closed as completed by bharadwaj-raju** 2016-08-13 07:41 UTC
