### ISSUE TITLE
Text is not inserted

### ISSUE THREAD

**Issue by jjnilton** [bharadwaj-raju/TextSuggest#42] opened 2017-01-09 17:32 UTC
I'm using Lubuntu 16.04 (through VirtualBox), when I press the keyboard shortcut it does show rofi and suggestions and aliases but it does not insert them.

In Firefox it opens a new window, probably related to issue #37. In other applications it does not seem to insert any text at all, tried in LXTerminal and Leafpad.

These are my keybinds:

```
    <keybind key="C-F1">
      <action name="Execute">
        <command>textsuggest --auto-selection</command>
      </action>
    </keybind>
    <keybind key="C-F2">
      <action name="Execute">
        <command>textsuggest</command>
      </action>
    </keybind>
    <keybind key="C-F3">
      <action name="Execute">
        <command>textsuggest --no-selection</command>
      </action>
    </keybind>
```

**Comment by bharadwaj-raju** [comment] 2017-01-10 10:04
What happens when you run it from the terminal?

**Comment by jjnilton** [comment] 2017-01-10 13:18
```
jose@work:~$ textsuggest
Running in replace mode.
Getting suggestions for word: 
Chosen word: custom=Teste de custom word
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 478, in <module>
    main()
  File "/usr/bin/textsuggest", line 471, in main
    processed_chosen_word = process_suggestion(chosen_word)
  File "/usr/bin/textsuggest", line 416, in process_suggestion
    if 'load-order.txt' in os.listdir(processor_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jose/.config/textsuggest/processors'
jose@work:~$ 
```

**Comment by bharadwaj-raju** [comment] 2017-01-12 15:08
Try this:

    $ mkdir ~/.config/textsuggest/processors

Meanwhile, I'll update the install.sh script.

**Comment by bharadwaj-raju** [comment] 2017-01-14 09:09
Probably fixed by 380e73d.

**Comment by bharadwaj-raju** [comment] 2017-01-22 09:28
@jjnilton Is it fixed? I'm waiting for a response so I can close this.

**Comment by jjnilton** [comment] 2017-01-22 12:08
@bharadwaj-raju yes, it works after making the directory. Thanks!

**Closed as completed** 2017-01-22 16:59 UTC

**Comment by actuallySIG** [comment] 2017-08-12 12:09
Neither of the two issues described have been fixed.

I'm using Ubuntu 16.04, and I still can't insert words unless I make the directory: 
> $ mkdir ~/.config/textsuggest/processors

Also, if a word is inserted somewhere in Firefox, it opens a new window.
I'm not experiencing this issue in Chromium. I haven't tried other browsers.

**Comment by bharadwaj-raju** [comment] 2017-08-14 08:31
@whitemarvin I'm sorry, the deb file must be having an outdated install script.

Can you try with git version? Just to see where the issue is.

**Comment by bharadwaj-raju** [comment] 2017-08-14 09:04
@whitemarvin As for the Firefox issue, can you tell me your desktop environment?

**Comment by actuallySIG** [comment] 2017-08-14 20:32
@bharadwaj-raju I'm using Unity.

Do I have to uninstall before trying the git version? Because TextSuggest doesn't show up in Ubuntu's package manager, and I can't remove it using the command line either:
>E: Unable to locate package textsuggest

**Comment by bharadwaj-raju** [comment] 2017-08-15 01:33
No, just use the git version's install script:

    $ sudo ./install.sh --uninstall
    $ sudo ./install.sh

**Comment by actuallySIG** [comment] 2017-08-15 13:14
I've installed the git version, but both issues are still present. Also, I've encountered the following error once, while testing TS in Firefox: http://i.imgur.com/XvOxvUU.png

**Comment by bharadwaj-raju** [comment] 2017-08-16 03:52
I'll fix it by next week, sorry. Meanwhile, try removing the `~/.config/textsuggest` directory and then re-installing.

Sorry.

**Comment by actuallySIG** [comment] 2017-08-16 11:04
I tried that, but now TextSuggest doesn't work at all. If I use TS in the command line, I get the following error:

> textsuggest -h

>Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 50, in <module>
    with open(custom_words_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dan/.config/textsuggest/Custom_Words.txt'

**Comment by bharadwaj-raju** [comment] 2017-08-17 03:21
I think I've found the problem; will fix by next week. Sorry.
